Elastic Load Balancer support
RiotGames/cinq-collector-aws pull request #16
Opened 2018-07-26 13:48 UTC by egor045

ELB support:
- Add resources.py to provide ELB class
- Add elbs.py to views/
- Add update_elbs() to region.py

2018-08-08 22:54 UTC, TheM0ng00se requested changes
See inline comments, other than that looks good, thanks for this.

2018-08-08 22:54 UTC, TheM0ng00se commented on cinq_collector_aws/region.py
> +                        'Added new EC2Instance {}/{}/{}'.format(
Do you mean ELB instead of E2Instance here?

2018-08-08 22:54 UTC, TheM0ng00se commented on cinq_collector_aws/views/elbs.py
> +        self.reqparse.add_argument('count', type=int, default=20, choices=[10, 20, 50])
I think the counts here feel a bit low? Unless you have specific reasons I'd recommend sticking to the count : 100 in args and choices of 25, 50, 100 to match the other resources

2018-08-09 10:53 UTC, egor045 commented
Log message updated
Counts updated to [25, 50, 100]

2018-08-09 15:25 UTC, TheM0ng00se approved these changes

2018-08-09 15:25 UTC, merged